### ISSUE TITLE
Add favicon to platform.grid.ai

### ISSUE THREAD

**Issue by stefanistrate** [gridai/gridai#105]
## 🚀 Feature

Please add the Grid.ai favicon to https://platform.grid.ai/ so that my nameless Chrome bookmarks are easily identifiable. 😄 

![Screenshot 2021-08-15 at 17 25 52](https://user-images.githubusercontent.com/3457859/129485379-6b1ecb05-d349-40fc-8dc2-d4d850121445.png)

Grid.ai is the 5th icon in the image above.

**Comment by sunitaprakash** [comment]
@stefanistrate Thanks for the feedback !!

**Comment by sunitaprakash** [comment]
@stefanistrate This has been fixed in today's release.
