### ISSUE TITLE
Runs are failing, but there's no error when running the script

### ISSUE THREAD

**Issue by cosmicBboy** [gridai/gridai#107]
## 🐛 Bug

I'm running the hello world example in https://docs.grid.ai/products/run-run-and-sweep-github-files but the run is failing even though the script completes with no errors.

![image](https://user-images.githubusercontent.com/2816689/130238488-077cc75d-6b0c-4bd4-ae65-1767311195bb.png)

Logs:
```
[experiment] [2021-08-20T13:08:19.872956+00:00] --------------------------------------------------
[experiment] [2021-08-20T13:08:19.872981+00:00] GPUS: There are 0 GPUs on this machine
[experiment] [2021-08-20T13:08:19.872986+00:00] --------------------------------------------------
[experiment] [2021-08-20T13:08:19.872990+00:00] PARAMS: I want to eat: 1 pizza
[experiment] [2021-08-20T13:08:19.872993+00:00] --------------------------------------------------
[experiment] [2021-08-20T13:08:19.872997+00:00] i can run any ML library like numpy, pytorch lightning, sklearn pytorch, keras, tensorflow
[experiment] [2021-08-20T13:08:19.873002+00:00] torch: tensor([0.8520]) numpy [0.10197159]
```

### Expected behavior

The run should be reported as "completed" instead of "failed"

### Current behavior

The run is reported as "failed"

### To Reproduce

Steps to reproduce the issue

Run the example in https://docs.grid.ai/products/run-run-and-sweep-github-files

### Environment

 - OS (e.g., Windows): MacOS
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version: v0.3.82

### Additional context

For reference, the run is `illegal-puffin-30` on my account username `cosmicBboy`

**Comment by luiscape** [comment]
@cosmicBboy i can see from the output that this is our demo world script, right?

What compute configs did you use?

**Comment by sunitaprakash** [comment]
@cosmicBboy This has been fixed in today's product release.
