### ISSUE TITLE
Failed experiment

### ISSUE THREAD

**Issue by hb563** [gridai/gridai#111]
## 🐛 Bug

I am getting a warning message that says I have an  incomplete requirments.txt file, and arguments in .sh file are not passed. The run runs with no issues locally, I only added 
`grid run --local dir --instance_type g4dn.xlarge` as well as specified the datastore after calling the .sh file.  
Despite the errors, it still launches an experiment.

### Expected behavior

run experiment

### Current behavior

explained above

### To Reproduce

Steps to reproduce the issue

This is from a private repo

### Environment

 - OS (e.g., Windows): Windows
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version:  0.3.87

### Additional context

Despite launching the experiment, it failed.

**Comment by hb563** [comment]
@sunitaprakash Do you have any recommendations to which would be better? I have tried wsl but I am facing trouble installing it. 
I wanted to mention that I ran a .sh file that was created on a mac system, I got the errors from bash, but it worked in grid.

**Comment by sunitaprakash** [comment]
@hb563 I think virtual docker environment might be better. Let me also confirm with team member.

**Comment by hhsecond** [comment]
Hi @hb563, Let me jump in here to help. Spinning up a grid session would be nice. We have had people try WSL without issues but there could be corner cases. If that doesn't work, I'll try creating a wandb session and give it a shot (I need to find a windows machine though). Let's also try to connect on a 1:1 if that's viable.

**Comment by sunitaprakash** [comment]
@hb563 Hope the information helped. Please free to ping us on slack so we can help you debug.

**Comment by hb563** [comment]
@sunitaprakash @hhsecond 
Apologies for the late reply. 

Thank you for the suggestions, I actually found an easier solution using the following:

`sed -i 's/\r$//' filename`

The only caveat is that it has to be used everytime the .sh file is altered.

Also, in terms of using wandb with grid, would it be possible to apply a wandb sweep using grid? 

If so, do you happen to have any examples?

**Comment by luiscape** [comment]
> Also, in terms of using wandb with grid, would it be possible to apply a wandb sweep using grid?

Weights and biases sweeps are currently incompatible with Grid. That's because WandB uses workers to manage experiments and those workers are not available in the experiment contexts.

Closing the issue as the main issue has been resolved. :)
