### ISSUE TITLE
datastore is not mounting complete dataset

### ISSUE THREAD

**Issue by cosmicBboy** [gridai/gridai#113]
## 🐛 Bug

I've downloaded a subset of the [kinetics](https://deepmind.com/research/open-source/kinetics) dataset and am trying to use it in a grid experiment.

The dataset structure is as follows:
```
datasets/
  kinetics/
    train/
      class1/
        file1.mp4
        file1.mp4
      class2/
        ...
    valid/
      class1/
        file1.mp4
        file1.mp4
      class2/
        ...       
```

I've tried several approaches and come up against 2 different bugs:

### Approach 1 and 2

Upload directly

```
grid datastore create --source datasets/kinetics --name kinetics
```

Use the `--compression` flag

```
grid datastore create --source datasets/kinetics --name kinetics --compression
```

This will successfully create the datastore. However, when I try to mount it to a run or session, the dataset is incomplete and only contains mp4 files for one of the dozen classes. For the rest, the directories are empty

### Approach 3: Try to compress by hand

Compressing that directory into a `tar.gz` archive succeeds during the cli upload phase, but the interface says something went wrong by optimizaing

```
grid datastore create --source kinetics.tar.gz --name kinetics
```

![image](https://user-images.githubusercontent.com/2816689/131180879-f1597cca-80de-4ec4-aa86-9e05b7dd188c.png)

### Expected behavior

With approach 1 and 2, I'd expect all the files in the directory to be present

For approach 3, I'd expect the created datastore to succeed in the optimization process

### Current behavior

See above

### To Reproduce

Steps to reproduce the issue

Sort of hard to reproduce without sending the data that I have locally.

### Environment

 - OS (e.g., Windows): MacOS
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version: v0.3.87

**Comment by jucor** [comment]
Hi @luiscape ! Is it still recommended to avoid nesting, a month later? I'm about to upload a dataset with nested folders, so thought I'd ask before spending time un-nesting. Thanks for any info!

**Comment by sunitaprakash** [comment]
@jucor @cosmicBboy 
The fix for this issue is now in production. Please let us know if you have any further issues here and appreciate your patience while we resolved the issue.
Regards,
Sunita

**Comment by jucor** [comment]
Awesome, thank you!

>
