### ISSUE TITLE
typo in datastore docs page

### ISSUE THREAD

**Issue by akihironitta** [gridai/gridai#114]
## 🐛 Bug
The following line should be corrected:

```diff
-grid datastores create --source imagenet_folder --name imagenet
+grid datastore create --source imagenet_folder --name imagenet
```

https://docs.grid.ai/products/add-data-to-grid-datastores/create-from-a-session#screen

### Environment

 - OS (e.g., Windows): Debian GNU/Linux
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version: `v0.3.87`

**Comment by sunitaprakash** [comment]
@akihironitta Thanks for reporting the issue in the docs .. it has been fixed.
