### ISSUE TITLE
Credits Balance

### ISSUE THREAD

**Issue by hb563** [gridai/gridai#117]
I am not sure who to speak to about this, but neither the website nor the documentation has any contact information with regards to any issues with credits.

**Comment by hb563** [comment]
I tried to upload a datastore and got the following error messages:

Datastore "dfs" failed to upload. Cannot read property 'datastoreVersion' of undefined
302 - Authorization failed for resource

**Comment by luiscape** [comment]
Hi @hb563, regarding the credits issue. Can you contact us via support@grid.ai?
