### ISSUE TITLE
Github repo as a requirement 

### ISSUE THREAD

**Issue by al967** [gridai/gridai#119]
## 🐛 Bug

Would it be possible to use a github repo as a requirment?

### Current behavior

the following is what I have in the requirements.txt file:
pip install git+https://github.com/somerepo
I am getting an error and a hint message that says "looks like a path... "

### To Reproduce

Steps to reproduce the issue

### Environment

 - OS (e.g., Windows):  
 - Browser (e.g., Chrome, Safari): 
 - CLI version:

**Comment by sunitaprakash** [comment]
@al967 Thanks for reporting the issue.

**Comment by hb563** [comment]
A package that I am using requires this to be installed:
`git+https://github.com/bp-kelley/descriptastorus`
It worked based on your instructions, but it is now requiring this package to be installed:
`rdkit`
I already had that in my requirements.txt (`rdkit-pypi`), but it seems that it clones repos first rather than installing packages.

**Comment by al967** [comment]
@sunitaprakash Yes, thank you it worked. However, it is now requiring another package to be installed, which I already listed in my requirements.txt file. It seems to be cloning the git hub first and skipping the packages, what would be a fix for this?

**Comment by sunitaprakash** [comment]
@al967 Can you share your Requirement file .. if you have sensitive data then send it via support@grid.ai so we can look at it

**Comment by al967** [comment]
@sunitaprakash  Yes, these are the contents:

alabaster==0.7.12
Babel==2.9.1
cloudpickle==1.6.0
colorama==0.4.4
cycler==0.10.0
docutils==0.17.1
google-auth==1.35.0
google-auth-oauthlib==0.4.5
grpcio==1.39.0
hyperopt==0.2.5
idna==3.2
imagesize==1.2.0
joblib==1.0.1
matplotlib 
mypy-extensions==0.4.3
networkx==2.6.2
packaging==21.0
pandas-flavor==0.2.0
pycairo==1.20.1
Pygments==2.10.0
PyYAML==5.4.1
rdkit-pypi
reportlab==3.5.68
requests==2.26.0
rsa==4.7.2
scikit-learn==0.24.2
scipy==1.7.1
sentry-sdk==1.3.1
snowballstemmer==2.1.0
Sphinx==4.1.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
subprocess32==3.5.4
tensorboard==2.6.0
tensorboardX==2.4
threadpoolctl==2.2.0
torch==1.9.0
tqdm==4.62.2
typed-argument-parser==1.7.1
typing-extensions==3.10.0.0
typing-inspect==0.7.1
urllib3==1.26.6
wandb==0.12.0
Werkzeug==2.0.1
xarray==0.19.0
git+https://github.com/bp-kelley/descriptastorus

**Comment by sunitaprakash** [comment]
Thanks, @al967.  Do you have the latest version of pip in the docker file?? Are you able to run the test locally without Grid.ai??

**Comment by al967** [comment]
@sunitaprakash Yes, I am able to run the test locally.

**Comment by sunitaprakash** [comment]
@al967 Can you try pip install -r requirements.txt and then pip install that particular one.

**Comment by al967** [comment]
@sunitaprakash You're right, got the same errors locally.

**Comment by sunitaprakash** [comment]
@al967 Did the above help you ?? pip install -r requirements.txt and then pip install that particular one
Should we close this ticket if the error is not related to Grid.ai ??

**Comment by al967** [comment]
I think a fix to this might be to use an environment.yml file, but there a special syntax for that instead of --localdir? As previous runs with Grid.ai failed when that was used.

**Comment by sunitaprakash** [comment]
@al967 
You can use conda env export > environment.yml and use that in the dockerfile like conda env create -f environment.yml. conda might do a better job than pip
Also check this out for examples 
there are some nice example of inserting pip statements in environment for conda here:
https://stackoverflow.com/questions/35245401/combining-conda-environment-yml-with-pip-requirements-txt
https://github.com/matterport/Mask_RCNN/issues/699

**Comment by sunitaprakash** [comment]
@al967 Closing this issue, since the failure is happening without Grid
