### ISSUE TITLE
Problem with sklearn dependency

### ISSUE THREAD

**Issue by plassi** [gridai/gridai#128]
When trying to execute a run on Grid.ai, the following problem occurs: 

_from sklearn import preprocessing, impute, compose 
ModuleNotFoundError: No module named 'sklearn'_ 

I tried requirements.txt containing: 
_scikit-learn==0.24.2_ 

After testing with Grid.ai session, I assume that sklearn is a part of Grid's own dependencies also on runs, so I also tried with empty requirements.txt and that didn't work. 

Everything works in a local environment. 

Please help.

**Comment by sunitaprakash** [comment]
Helloa @plassi 

Thank you for reaching out to us. Our team will look into your ticket and get back to you shortly.

**Comment by sunitaprakash** [comment]
Hi !  @plassi Can you share a little more details for us to reproduce the issue?  Do you have Github repo that you can share or snippet of code that might be causing the issue. 
Also can you please the output for "grid user".

You can also try to use YML file 
https://docs.grid.ai/products/run-run-and-sweep-github-files/yaml-configs

To run the command from the CLI grid run --name RUN_NAME --config config.yml test.py

in the config file you can try to use the actions to install dependies 
   actions:
      on_image_build:
        - apt-get update
        - apt install -y libgl1-mesa-glx
        
Please share the details when you get a chance.

**Comment by plassi** [comment]
Using '--dependency_file requirements.txt' option with the run fixed this problem for me.

 Thanks for such a great product!
