### ISSUE TITLE
yaml config environment variables not working

### ISSUE THREAD

**Issue by cosmicBboy** [gridai/gridai#130]
## 🐛 Bug

using the `train.environment` key in yaml config doesn't work. When I print `os.getenv("KEY")` in my script it prints out `None`

### Expected behavior

environment variables should be injected into the script's runtime

### Current behavior

The variable doesn't exist

### To Reproduce

Steps to reproduce the issue

in yaml file:

```
compute:
  train:
    environment:
      KEY: VALUE
```

in python file:

```
import os

print(os.getenv("KEY"))
# output: None
```

### Environment

 - OS (e.g., Windows): MacOS
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version: v0.3.92

### Additional context

NA

**Comment by sunitaprakash** [comment]
Hi! @cosmicBboy 
Thank you for your feedback. Our team will look into your ticket and get back to you shortly.

**Comment by sunitaprakash** [comment]
Hi! @cosmicBboy 
I’m reaching out to you regarding your ticket. Our team is working on your issue. Thanks for your patience and support

**Comment by oojo12** [comment]
THis has been fixed.
