### ISSUE TITLE
Some runs fail but it is impossible to see the stdout logs(or any other logs for that matter)

### ISSUE THREAD

**Issue by sofeikov** [gridai/gridai#133]
## 🐛 Bug

Some of the runs I submit, fail. I know they run absolutely fine locally, and that if I resubmit them, they will also run fine. However, the UI displayed them as failed, and when I attempt to look at the logs, I just see infinite loading gif. 

### Expected behavior

I should be able to see the logs of the failed job. I can't. No building logs, not stdout logs, nothing. 

### Current behavior

No building logs, not stdout logs, nothing. 

### To Reproduce

I suppose we can get in touch so I tell you my account ID and run id, so that is investigated?

### Environment

 - OS Ubuntu Linux
 - Browser: chrome Version 93.0.4577.63 (Official Build) (64-bit)
 - CLI version:
                              Grid CLI (v0.3.98)
                            https://docs.grid.ai

### Additional context

n/a

**Comment by sunitaprakash** [comment]
Hi! @drsealks 
Thank you for your feedback. Our team will look into your ticket and get back to you shortly.

**Comment by sunitaprakash** [comment]
@drsealks sorry about the delay. Can you please email us your account id and run id at support@grid.ai.  You also join our [gridai-community.slack.com](url)

**Comment by drsealks** [comment]
@sunitaprakash I've already deleted those stale runs. However, I will be creating more of them, I'm pretty sure it is going to happen again. When it does, I will mail it to that address with the details. Thanks!

**Comment by sunitaprakash** [comment]
@drsealks You should be able to see the log when the runs fail. Yes please share the details if the error repeats again. 
If you are using CLI , please make sure it is updated.  
pip install lightning-grid --upgrade

**Comment by simbara** [comment]
I have noticed the same issue and I *think* it happens if my local git repo isn't in sync with the remote one.
