### ISSUE TITLE
Runs and Sessions not loading

### ISSUE THREAD

**Issue by alexandercort** [gridai/gridai#139]
## 🐛 Bug

Runs and session are not loading when using the UI
Cannot see my own or others runs or session
Teams

### Expected behavior

Visible sessions and runs across team

### Current behavior

See bug above

### To Reproduce

https://video.drift.com/v/abu4jCAKea5/

Others on my team have confirmed

### Environment

 - OS (e.g., Windows): Mac
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version: Using the UI

**Comment by sunitaprakash** [comment]
@alexandercort 
The fix for this issue is now in production. Please let us know if you have any further issues here and appreciate your patience while we resolved the issue.
Regards,
Sunita
