### ISSUE TITLE
Datastore mount directory does not appear in interactive session

### ISSUE THREAD

**Issue by SaeedShurrab** [gridai/gridai#141]
## 🐛 Bug
When mounting the datastore to the interactive session, I do  not get the option to specify the directory of the datastore in the created session, even when creating the session the default datastore/ directory does not exist

### Expected behavior

the expected behavior is to specify mount directory upon session creation or the default datastore/ directory in the working space inside the session

### Current behavior

none of the previously described behaviors appear to work for me.

### Environment

 - Browser (e.g., Chrome, Safari):

**Comment by sunitaprakash** [comment]
Hello @SaeedShurrab

Thanks for reaching out. Yeah, we had some changes in the product recently,  the datastore directory in the session is in the /datastores directory. 

Regards,
Sunita

**Comment by SaeedShurrab** [comment]
The problem is this directory does not apear at all in th session, i just get conda qnd work directories.

**Comment by sunitaprakash** [comment]
@SaeedShurrab  When you created the session did you attach it to the [session?]
https://docs.grid.ai/products/sessions/attaching-datastores

**Comment by SaeedShurrab** [comment]
Yes, of course, but i did not find the datastore directory

**Comment by sunitaprakash** [comment]
On you on Slack gridai-community.slack.com then we can chat on slack

**Comment by sunitaprakash** [comment]
@SaeedShurrab Glad that you found the datastore directory.
