### ISSUE TITLE
ERROR: Command errored out with exit status 1 when installing grid CLI

### ISSUE THREAD

**Issue by SaeedShurrab** [gridai/gridai#143]
## 🐛 Bug

I am trying to install grid CLI in my python environment as well as a docker container with python 3.8.1 but I get errors when installing it that prevent the successful installation

### Expected behavior

successful installation of grid CLI

### Current behavior
I get this error

> ERROR: Command errored out with exit status 1:
   command: /home/saeed/Desktop/oop/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_836jsms
       cwd: /tmp/pip-install-w00brjau/cytoolz/
  Complete output (7 lines):
  ALERT: Cython not installed.  Building without Cython.
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
error: invalid command 'bdist_wheel'
ERROR: Failed building wheel for cytoolz
Running setup.py clean for cytoolz
Building wheel for gql (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/saeed/Desktop/oop/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w00brjau/gql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w00brjau/gql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v67tuy4p
cwd: /tmp/pip-install-w00brjau/gql/
Complete output (6 lines):
 usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'bdist_wheel'
ERROR: Failed building wheel for gql
Running setup.py clean for gql
Building wheel for docopt (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/saeed/Desktop/oop/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w00brjau/docopt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w00brjau/docopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yvtalywc
cwd: /tmp/pip-install-w00brjau/docopt/
Complete output (6 lines):
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'bdist_wheel'
ERROR: Failed building wheel for docopt
Running setup.py clean for docopt
Failed to build cytoolz gql docopt
Installing collected packages: six, grpcio, pyparsing, packaging, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, certifi, idna, urllib3, charset-normalizer, requests, protobuf, googleapis-common-protos, google-api-core, google-cloud-core, pytz, tqdm, docopt, yarg, pipreqs, python-dateutil, jmespath, botocore, s3transfer, boto3, google-crc32c, google-resumable-media, google-cloud-storage, commonmark, pygments, colorama, rich, toolz, cytoolz, marshmallow, mypy-extensions, typing-extensions, typing-inspect, marshmallow-enum, dataclasses-json, requests-toolbelt, websockets, graphql-core, multidict, yarl, gql, tzdata, backports.zoneinfo, pytz-deprecation-shim, tzlocal, yaspin, ulid-py, humanize, backoff, monotonic, analytics-python, arrow, PyYAML, click, numpy, pyjwt, google-cloud, lightning-grid
    Running setup.py install for docopt ... done
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: /home/saeed/Desktop/oop/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bhwtsaz2/install-record.txt --single-version-externally-managed --compile --install-headers /home/saeed/Desktop/oop/venv/include/site/python3.8/cytoolz
         cwd: /tmp/pip-install-w00brjau/cytoolz/
    Complete output (56 lines):
    ALERT: Cython not installed.  Building without Cython.
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/_version.py -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.8/cytoolz
    creating build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    creating build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/cytoolz
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/saeed/Desktop/oop/venv/include -I/usr/include/python3.8 -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.8/cytoolz/dicttoolz.o
    cytoolz/dicttoolz.c:19:10: fatal error: Python.h: No such file or directory
       19 | #include "Python.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
ERROR: Command errored out with exit status 1: /home/saeed/Desktop/oop/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bhwtsaz2/install-record.txt --single-version-externally-managed --compile --install-headers /home/saeed/Desktop/oop/venv/include/site/python3.8/cytoolz Check the logs for full command output.`

### To Reproduce

pip install lightning-grid --upgrade

### Environment

 - OS (e.g., Windows): linux ubuntu with python 3.8.1, docker container with linux environment and python 3.7.11

 - CLI version: as-is with no specification 

#### Complete installation progress
> Collecting lightning-grid
  Downloading lightning_grid-0.5.1-py2.py3-none-any.whl (466 kB)
     |████████████████████████████████| 466 kB 322 kB/s 
Collecting grpcio<2.0.0,>=1.33.2
  Downloading grpcio-1.42.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 391 kB/s 
Collecting packaging>=20.7
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 265 kB/s 
Collecting google-cloud-core>=1.3.0
  Downloading google_cloud_core-2.2.1-py2.py3-none-any.whl (29 kB)
Collecting pytz
  Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
     |████████████████████████████████| 503 kB 314 kB/s 
Collecting tqdm<5.0.0,>=4.0
  Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 243 kB/s 
Collecting pipreqs
  Downloading pipreqs-0.4.11-py2.py3-none-any.whl (32 kB)
Collecting boto3<2,>=1.15
  Downloading boto3-1.20.17-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 354 kB/s 
Collecting google-cloud-storage>=1.28.1
  Downloading google_cloud_storage-1.43.0-py2.py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 430 kB/s 
Collecting urllib3<2.0.0,>=1.26
  Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 385 kB/s 
Collecting rich>=10.2
  Downloading rich-10.15.1-py3-none-any.whl (214 kB)
     |████████████████████████████████| 214 kB 327 kB/s 
Collecting cytoolz
  Downloading cytoolz-0.11.2.tar.gz (481 kB)
     |████████████████████████████████| 481 kB 323 kB/s 
Collecting protobuf<4.0.0,>=3.2
  Downloading protobuf-3.19.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 565 kB/s 
Collecting dataclasses-json
  Downloading dataclasses_json-0.5.6-py3-none-any.whl (25 kB)
Collecting requests<3.0.0,>=2.24
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 118 kB/s 
Collecting requests-toolbelt<1.0.0,>=0.9.1
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 270 kB/s 
Collecting websockets<10.0,>=9.0
  Downloading websockets-9.1-cp38-cp38-manylinux2010_x86_64.whl (102 kB)
     |████████████████████████████████| 102 kB 482 kB/s 
Collecting gql<4.0.0,>=3.0.0a4
  Downloading gql-3.0.0b1.tar.gz (119 kB)
     |████████████████████████████████| 119 kB 538 kB/s 
Collecting googleapis-common-protos>=1.52.0
  Downloading googleapis_common_protos-1.53.0-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 562 kB/s 
Collecting tzlocal
  Downloading tzlocal-4.1-py3-none-any.whl (19 kB)
Collecting yaspin<1.0.0,>=0.16
  Downloading yaspin-0.18.0-py2.py3-none-any.whl (26 kB)
Collecting ulid-py
  Downloading ulid_py-1.1.0-py2.py3-none-any.whl (25 kB)
Collecting google-api-core>=1.22.2
  Downloading google_api_core-2.2.2-py2.py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 303 kB/s 
Collecting google-auth>=1.22.0
  Downloading google_auth-2.3.3-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 291 kB/s 
Collecting humanize<4.0.0,>=3.0
  Downloading humanize-3.13.1-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 291 kB/s 
Collecting analytics-python
  Downloading analytics_python-1.4.0-py2.py3-none-any.whl (15 kB)
Collecting arrow
  Downloading arrow-1.2.1-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 175 kB/s 
Collecting PyYAML<6.0,>=5.0
  Downloading PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
     |████████████████████████████████| 662 kB 454 kB/s 
Collecting click>=7.0.0
  Downloading click-8.0.3-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 335 kB/s 
Collecting numpy
  Downloading numpy-1.21.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 716 kB/s 
Collecting pyjwt<2.0.0,>=1.7.0
  Downloading PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting google-cloud>=0.34.0
  Downloading google_cloud-0.34.0-py2.py3-none-any.whl (1.8 kB)
Collecting six>=1.5.2
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.6-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 184 kB/s 
Collecting docopt
  Downloading docopt-0.6.2.tar.gz (25 kB)
Collecting yarg
  Downloading yarg-0.1.9-py2.py3-none-any.whl (19 kB)
Collecting botocore<1.24.0,>=1.23.17
  Downloading botocore-1.23.17-py3-none-any.whl (8.4 MB)
     |████████████████████████████████| 8.4 MB 533 kB/s 
Collecting s3transfer<0.6.0,>=0.5.0
  Downloading s3transfer-0.5.0-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 646 kB/s 
Collecting jmespath<1.0.0,>=0.7.1
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting google-resumable-media<3.0dev,>=1.3.0; python_version >= "3.6"
  Downloading google_resumable_media-2.1.0-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 442 kB/s 
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 594 kB/s 
Collecting pygments<3.0.0,>=2.6.0
  Downloading Pygments-2.10.0-py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 917 kB/s 
Collecting colorama<0.5.0,>=0.4.0
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting toolz>=0.8.0
  Downloading toolz-0.11.2-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 419 kB/s 
Collecting marshmallow<4.0.0,>=3.3.0
  Downloading marshmallow-3.14.1-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 508 kB/s 
Collecting typing-inspect>=0.4.0
  Downloading typing_inspect-0.7.1-py3-none-any.whl (8.4 kB)
Collecting marshmallow-enum<2.0.0,>=1.5.1
  Downloading marshmallow_enum-1.5.1-py2.py3-none-any.whl (4.2 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 454 kB/s 
Collecting idna<4,>=2.5; python_version >= "3"
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 168 kB/s 
Collecting charset-normalizer~=2.0.0; python_version >= "3"
  Downloading charset_normalizer-2.0.8-py3-none-any.whl (39 kB)
Collecting graphql-core<3.2,>=3.1.5
  Downloading graphql_core-3.1.6-py3-none-any.whl (189 kB)
     |████████████████████████████████| 189 kB 464 kB/s 
Collecting yarl<2.0,>=1.6
  Downloading yarl-1.7.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (308 kB)
     |████████████████████████████████| 308 kB 485 kB/s 
Collecting pytz-deprecation-shim
  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting backports.zoneinfo; python_version < "3.9"
  Downloading backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl (74 kB)
     |████████████████████████████████| 74 kB 289 kB/s 
Requirement already satisfied, skipping upgrade: setuptools>=40.3.0 in ./venv/lib/python3.8/site-packages (from google-api-core>=1.22.2->lightning-grid) (44.0.0)
Collecting rsa<5,>=3.1.4; python_version >= "3.6"
  Downloading rsa-4.8-py3-none-any.whl (39 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 707 kB/s 
Collecting backoff==1.10.0
  Downloading backoff-1.10.0-py2.py3-none-any.whl (31 kB)
Collecting python-dateutil>2.1
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 679 kB/s 
Collecting monotonic>=1.5
  Downloading monotonic-1.6-py2.py3-none-any.whl (8.2 kB)
Collecting google-crc32c<2.0dev,>=1.0
  Downloading google_crc32c-1.3.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (37 kB)
Collecting mypy-extensions>=0.3.0
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting typing-extensions>=3.7.4
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting multidict>=4.0
  Downloading multidict-5.2.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (187 kB)
     |████████████████████████████████| 187 kB 721 kB/s 
Collecting tzdata; python_version >= "3.6"
  Downloading tzdata-2021.5-py2.py3-none-any.whl (339 kB)
     |████████████████████████████████| 339 kB 650 kB/s 
Collecting pyasn1>=0.1.3
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 489 kB/s 
Building wheels for collected packages: cytoolz, gql, docopt
  Building wheel for cytoolz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/saeed/Desktop/oop/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_836jsms
       cwd: /tmp/pip-install-w00brjau/cytoolz/
  Complete output (7 lines):
  ALERT: Cython not installed.  Building without Cython.
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  error: invalid command 'bdist_wheel'
  ERROR: Failed building wheel for cytoolz
  Running setup.py clean for cytoolz
  Building wheel for gql (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/saeed/Desktop/oop/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w00brjau/gql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w00brjau/gql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v67tuy4p
       cwd: /tmp/pip-install-w00brjau/gql/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  error: invalid command 'bdist_wheel'
  ERROR: Failed building wheel for gql
  Running setup.py clean for gql
  Building wheel for docopt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/saeed/Desktop/oop/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w00brjau/docopt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w00brjau/docopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yvtalywc
       cwd: /tmp/pip-install-w00brjau/docopt/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  error: invalid command 'bdist_wheel'
  ERROR: Failed building wheel for docopt
  Running setup.py clean for docopt
Failed to build cytoolz gql docopt
Installing collected packages: six, grpcio, pyparsing, packaging, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, certifi, idna, urllib3, charset-normalizer, requests, protobuf, googleapis-common-protos, google-api-core, google-cloud-core, pytz, tqdm, docopt, yarg, pipreqs, python-dateutil, jmespath, botocore, s3transfer, boto3, google-crc32c, google-resumable-media, google-cloud-storage, commonmark, pygments, colorama, rich, toolz, cytoolz, marshmallow, mypy-extensions, typing-extensions, typing-inspect, marshmallow-enum, dataclasses-json, requests-toolbelt, websockets, graphql-core, multidict, yarl, gql, tzdata, backports.zoneinfo, pytz-deprecation-shim, tzlocal, yaspin, ulid-py, humanize, backoff, monotonic, analytics-python, arrow, PyYAML, click, numpy, pyjwt, google-cloud, lightning-grid
    Running setup.py install for docopt ... done
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: /home/saeed/Desktop/oop/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bhwtsaz2/install-record.txt --single-version-externally-managed --compile --install-headers /home/saeed/Desktop/oop/venv/include/site/python3.8/cytoolz
         cwd: /tmp/pip-install-w00brjau/cytoolz/
    Complete output (56 lines):
    ALERT: Cython not installed.  Building without Cython.
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/_version.py -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.8/cytoolz
    creating build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.8/cytoolz/curried
    copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.8/cytoolz
    creating build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.8/cytoolz/tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/cytoolz
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/saeed/Desktop/oop/venv/include -I/usr/include/python3.8 -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.8/cytoolz/dicttoolz.o
    cytoolz/dicttoolz.c:19:10: fatal error: Python.h: No such file or directory
       19 | #include "Python.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
ERROR: Command errored out with exit status 1: /home/saeed/Desktop/oop/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w00brjau/cytoolz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bhwtsaz2/install-record.txt --single-version-externally-managed --compile --install-headers /home/saeed/Desktop/oop/venv/include/site/python3.8/cytoolz Check the logs for full command output.

**Comment by sunitaprakash** [comment]
@SaeedShurrab As mentioned in the Slack message you were able to install GRID CLI was successfully installed on python 3.7.12 in docker container.

Also for the gcc install error you can also try the " sudo apt install build-essential"
