### ISSUE TITLE
"link to Github account" is broken

### ISSUE THREAD

**Issue by nrgarach** [gridai/gridai#147]
### Expected behavior

Take me to Github login to link grid.ai to it

### Current behavior

Page not found error on page when trying to link to github account 

### To Reproduce

Steps to reproduce the issue

1) Visit https://docs.grid.ai/start-here/typical-workflow-cli-user
2) Visit link on the text "link to Github account"
3) It takes to https://docs.grid.ai/start-here/private-repos and shows page not found

### Environment

 - OS (e.g., Windows):
 - Browser (e.g., Chrome, Safari):
 - CLI version:

**Comment by essiequoi** [comment]
Hi @nrgarach thanks for reporting this issue! It's been resolved, so you should be able to see instructions on how to link to Github private repos [here](https://docs.grid.ai/start-here/private-repos). Let me know if you have anymore trouble.

**Comment by essiequoi** [comment]
Hi @nrgarach thanks for reporting this issue! It's been resolved, so you should be able to see instructions on how to link to Github private repos [here](https://docs.grid.ai/start-here/private-repos). Let me know if you have anymore trouble.

**Comment by nrgarach** [comment]
Works, thank you
