### ISSUE TITLE
Utilities or workflow to test image creation

### ISSUE THREAD

**Issue by williamFalcon** [gridai/gridai#24]
I am excited to test the use of the custom grid actions (e.g. using a
    # Actions need to be passed as one command
    # per line.
    actions:
      on_image_build:
          - bash my_script.sh
but am terrified to try it without a way to test out the images.  Is there a process to do so.   Can we see the log of the image building for example?  My understanding is that Stdout Logs only shows the post-image run?

**Comment by sunitaprakash** [comment]
@jlperla We made enhancements to pre-run logs , it is called Build Logs. You can test out the custom grid actions and you should logs for those in Build Logs
Please let us know if that works for you
