### ISSUE TITLE
Missing metrics from csv

### ISSUE THREAD

**Issue by williamFalcon** [gridai/gridai#28]
On my recent run linear-zero-phi-trials it looks like everything succeeded and if you look at the artifacts, the test errors/etc. were calculated, but they aren't showing in the UI or the CSV for all of them.  But all of the logged stuff in the train and validation phase appears to be there.  See this screenshot.  As always, I don't especially care about these exact numbers, was just experimenting with ways to get multipe trials for a given experiment working.

**Comment by jlperla** [comment]
I think you can close. Will add a PL one of I can reproduce
