### ISSUE TITLE
`less` should be installed by default

### ISSUE THREAD

**Issue by turian** [gridai/gridai#30]
It's a small package and a useful command.

**Comment by nmiculinic** [comment]
Anything else you'd find useful, but it's missing?

**Comment by turian** [comment]
@nmiculinic TBH for sessions (I don't use runs yet) I would like some sort of sane way to define a common pre-launch setup:
* apt-get install certain package
* pip3 install certain packages
* make run a few shell scripts to pull my repo and git submodule init
* create dotfiles so I'm not stuck with emacs or nano or whatever it is

**Comment by sunitaprakash** [comment]
@turian We have installed less package on session. Hope it helps.

**Comment by sunitaprakash** [comment]
@turian I have created a separate feature request for the Session pre-launch setup    ###https://github.com/gridai/gridai/issues/46
