### ISSUE TITLE
"Connect via SSH" should give full session name

### ISSUE THREAD

**Issue by turian** [gridai/gridai#31]
```
grid interactive ssh longproject...name
```

is an unhelpful copy-and-paste

**Comment by williamFalcon** [comment]
is that on the side modal?

**Comment by turian** [comment]
In the right modal labeled "SSH into Session" when you click on the shell icon in sessions

**Comment by nmiculinic** [comment]
I've also seen CLI shortening long session names with `...` FYI

**Comment by sunitaprakash** [comment]
Hi! @turian 
We have fixed the problem with long name for the session  in latest CLI .. 
please update the CLI - pip3 install lightning-grid --upgrade
Please let me know if the issue is fixed for you.
Thanks
