### ISSUE TITLE
Unable to create datastore in CLI version v0.3.68

### ISSUE THREAD

**Issue by essiequoi** [gridai/gridai#40]
## 🐛 Bug

Opened by: `leifdenby` 

I'm having issues creating a datastore. Two things (I'm using the CLI because my dataset is quite large):

1. When trying to create a datastore from a folder containing my data the script attempts to make a temporary tar-ball in my home directory. However my home-directory has a disk quota on it. It would be nice if it was possible to pass in a flag saying where the temporary file should be stored (or just use `/tmp` instead, that is usually where applications put there temporary files)
2. When creating the tar-ball myself and trying to create the datastore (`grid datastores create --source goes16__Nx256_s200000.0_N1000study_N10000train.tar.gz --name Nx256_s200000.0_N1000study_N10000train`) I get the following error: `TransportServerError: 502 Server Error: Bad Gateway for url: https://platform.grid.ai/graphql`

 - CLI version: v0.3.68

**Comment by rlizzo** [comment]
Hi @leifdenby 

For number (2), can you confirm that other CLI commands are working for you? (try running `grid status` or `grid history` and let me know if the same `502 Error` occurs). Also, is this a persistent or intermittent issue? (does this work if you retry the command?) 

Thanks!

**Comment by leifdenby** [comment]
> For number (2), can you confirm that other CLI commands are working for you? (try running `grid status` or `grid history` and let me know if the same `502 Error` occurs)

Yes, just ran both and they worked ok. I got a table with "no active jobs" and a table with the one job I've previously run

I got a different error this time. This again seems to be because of my home-directory not having enough space for the temporary file (my homedir is `/nfs/see-fs-02_users/earlcd/`):

```bash
$ /nfs/a321/earlcd/ml-data/tiles/goes16 > grid datastores create --source goes16__Nx256_s200000.0_N1000study_N10000train.tar.gz --name Nx256_s200000.0_N1000study_N10000train
✘ Packaging datastore Nx256_s200000.0_N1000study_N10000train...

            Whoops, your datastore creation failed!

            To resume, run:

            grid datastores resume Nx256_s200000.0_N1000study_N10000train-v2
            
Error: Failed to upload datastore Nx256_s200000.0_N1000study_N10000train. Command 'tar -C /nfs/a321/earlcd/ml-data/tiles/goes16 -cvf /nfs/see-fs-02_users/earlcd/.grid/datastores/bb5f2fb9-1260-4f36-885c-d5a484dec00d/data.tar.gz goes16__Nx256_s200000.0_N1000study_N10000train.tar.gz' returned non-zero exit status 2.
```

With the error I got previously I didn't get the "Packaging datastore..." message. It seems like the datastores command always create a new tar-ball even when the data is already in a tar-ball?

**Comment by luiscape** [comment]
Hey there @leifdenby! Thank you for the bug report.

Regarding

> It seems like the datastores command always create a new tar-ball even when the data is already in a tar-ball?

Yes, that's correct. The current behavior is that we tarball any local targets before uploading it to the backend. We have learned that quite a few folks are in the same situation that you are in -- folks already have a tarball and they just want to create a datastore off of that; so we adding that feature now. It'll work like this:

- if you have a tarball already (either `tar`, `tar.gz`, or `zip`) we'll skip the packaging process
- we'll automatically unpackage the file on the other end so you don't have to do that manually whenever datastores are mounted

Is this what you would expect?

We are targeting this feature to be available in our next release.

PS: Regarding 

> TransportServerError: 502 Server Error:

we observed a transient API instability earlier today. We are addressing this issue in a separate thread.

**Comment by leifdenby** [comment]
> Is this what you would expect?

Yes, that would be perfect!

In the meantime I have created `/tmp/grid-datastores` and symlinked it to `~/.grid/datastores` and passed in a non tar-ball as the "source". This has allowed me to create a datastore and it was successfully uploaded.

I think it would be nice to allow the "datastores" path to be configurable (in case it's used more than just to create a temporary file to upload) or be set with a flag to the `create datastores` cli-command (in case the location is only needed temporarily).

**Comment by luiscape** [comment]
> I think it would be nice to allow the "datastores" path to be configurable (in case it's used more than just to create a temporary file to upload) or be set with a flag to the create datastores cli-command (in case the location is only needed temporarily).

Interesting. I'll keep you posted on this one. cc @tnachen

**Comment by sunitaprakash** [comment]
Hi! @leifdenby 

We have released the fix for the datastore getting the 502 error. Please try it when you get a chance.** . 
We are still working on the fix for problem 1 .. will message you once that is fixed.
