### ISSUE TITLE
Add Utilities Interactive Sessions

### ISSUE THREAD

**Issue by luiscape** [gridai/gridai#43]
## 🚀 Feature

From @leifdenby.

It'd be great to have the following utilities installed in Jupyter Lab by default:

* `tree`
* `tmux`
* `gpustat`: https://github.com/wookayin/gpustat

### Description

Those are very useful for regular and GPU-based workloads.

**Comment by sunitaprakash** [comment]
We have the utilities (tree, tmux, gpustat) on interactive session / Jupyter Lab installed by default with the latest prod.
