### ISSUE TITLE
Error when adding a new SSH key

### ISSUE THREAD

**Issue by awwong1** [gridai/gridai#50]
## 🐛 Bug

An error occurs when I try to add my SSH to Grid (using CLI or the web application).

### Expected behavior

I can add my SSH key to Grid without exceptions occurring.

### Current behavior

![Screenshot_20210502_140438](https://user-images.githubusercontent.com/2760111/116826105-a1305f00-ab4f-11eb-9eab-1ee9f4b5d597.png)

### To Reproduce

Attempted to add this valid SSH public key:

```text
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIPKXZ2Vo8FOd2+bd9U4EvS0kvsCPbpiWrraLXTdClVu alex@udia.ca Spring, 2020
```

### Environment

 - OS (e.g., Windows): Debian GNU/Linux 10
 - Browser (e.g., Chrome, Safari): Firefox Browser 88.0 (64 -bit)
 - CLI version: `Grid CLI (v0.3.68)`

**Comment by Sunitagrid** [comment]
@awwong1 Can you try this commands for ssh to see if it works .. 
ssh-keygen -t ed25519 -C "your_email@example.com"
grid ssh-keys add lit_key ~/.ssh/ed25519.pub

We will also debug at our end.

**Comment by awwong1** [comment]
Perhaps the problem occurs because of the comma character in the comment section of the key?

**Comment by nmiculinic** [comment]
```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIPKXZ2Vo8FOd2+bd9U4EvS0kvsCPbpiWrraLXTdClVu alex@udia.ca Spring,2020
```

Can you try without whitespace in the SSH comment? Or use something else, like a hyphen

**Comment by Sunitagrid** [comment]
@awwong1 Glad to know that ssh is working for you
