### ISSUE TITLE
Frontend issues during Cifar-10 Example

### ISSUE THREAD

**Issue by essiequoi** [gridai/gridai#58]
## 🐛 Bug

Opened by Matt Koh

Tried to run the Cifar-10 example from the UI dashboard, but was unable to due to UI glitches. 

### Expected behavior

The expectation was that clicking on the example would populate all the required fields in the run flow and that submitting the experiment would succeed without error. 

### Current behavior

Unable to submit the run - the UI does not respond. 

### To Reproduce

i click run. the box turns a dark gray color, but the dialog doesn’t close or otherwise indicate that something happens. Note: It says there are no branches to be found though. 

if i X out of  the dialog  and refresh, it pops up again :smile:
and the runs list is still empty

### Environment

 - OS (e.g., Windows): MacOS
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version: N/A

### Additional context

i tried again with browser tools and now i see this:

![image](https://user-images.githubusercontent.com/13732925/118137188-ec116880-b3d2-11eb-96d3-66cd8bc38d8c.png)

the difference is that when it worked, I manually entered the github repo
the time it failed, the repo was already populated

when I manually enter the repo, it puts a branch name in and asks me to pick the file
if it’s already filled in (like it is when you click the suggested example), then the git branch isn’t master (it says “no results” and then I got that error above

**Comment by sunitaprakash** [comment]
@Matt Thanks for reporting the problem. We are working on fixing it.. the workaround for it is to select the Github repo  (gridai/hello_mnists) and select the script (pl_cifar10.py)  , then click Start.

**Comment by sunitaprakash** [comment]
Matt the cifar-10 example has been fixed
