### ISSUE TITLE
Cloning private github repo doesn't work

### ISSUE THREAD

**Issue by BarRoszak** [gridai/gridai#59]
## 🐛 Bug

After starting a session and connecting via ssh I am not able to clone private github repo even though I have github account integrated.

### Environment

 - CLI version: lightning-grid==0.3.70

### Additional context

<img width="574" alt="Screenshot 2021-05-17 at 14 35 16" src="https://user-images.githubusercontent.com/75304439/118489425-1a69ad80-b71d-11eb-9564-33968f32b7e8.png">

**Comment by essiequoi** [comment]
Just adding a bit more context to this issue:

1. Bartek and his colleague are currently evaluating Teams, but in the meantime Bartek was logged into his colleague's Grid account and tried to integrate his own (Bartek's) private repos to this Grid account. This posed some issues. 

2. Bartek then logged into his own Grid account and attempted to integrate with his Github repo, but when he tried to "Grant Access" it just redirected him to the Grid landing page and did not grant access. 

3. Now he has asked his colleague to remove the private repo accent from his account, but his colleague is unable to.

**Comment by essiequoi** [comment]
Update: Bartek revoked github access from his colleague Dawid's account and was successfully able to connect his own Grid account to his private Github repos

**Comment by essiequoi** [comment]
@BarRoszak is still unable to clone private repo even after making sure the proper accesses have been granted. 

cc @tnachen 

![image](https://user-images.githubusercontent.com/13732925/118505099-1aa48180-b6fa-11eb-90b4-cc5dcc85ed85.png)

![image](https://user-images.githubusercontent.com/13732925/118505123-2132f900-b6fa-11eb-852b-bcc38131158f.png)

![image](https://user-images.githubusercontent.com/13732925/118505151-26904380-b6fa-11eb-931c-5f257b82b6e9.png)

**Comment by essiequoi** [comment]
This has been resolved! It was discovered that the user needed to grant access to the Github organization to which the private repo belongs. We will improve our documentation and UX for this use case.
