### ISSUE TITLE
Cannot list files in private repo (UI)

### ISSUE THREAD

**Issue by essiequoi** [gridai/gridai#60]
## 🐛 Bug

Opened by: Felix

When creating a new run from the UI, if i open a folder in my private repo grid does not list files.

I would expect to see all python files within all directories in the repo

The directory appears to be empty even though there are python files in it

Steps to reproduce the issue

1. Go to UI to create new run
2. Enter private repo which has sub-directories and python files in a sub-directory
3. Attempt to navigate to that sub-directory to locate the file 

### Environment

 - OS (e.g., Windows):
 - Browser (e.g., Chrome, Safari):

### Additional context

![image](https://user-images.githubusercontent.com/13732925/118975775-5467c900-b942-11eb-8546-e6f9124f9262.png)
![image](https://user-images.githubusercontent.com/13732925/118975816-5d589a80-b942-11eb-9888-acee55aa2cb1.png)

**Comment by luiscape** [comment]
@essiequoi this is certainly a bug. 

There's a known issue in which we can't list files when repositories have changed names, otherwise repository listing should be there as expected.

**Comment by sunitaprakash** [comment]
Workaround for this is to paste the link directly to the github script.
