### ISSUE TITLE
CLI: `grid session` not listed in `grid --help`

### ISSUE THREAD

**Issue by robert-s-lee** [gridai/gridai#61]
## 🐛 Bug

`grid session` and `grid interactive` are interchangeable in docs; however, `grid --help` does not list `grid session`  

- `grid interactive` [here](https://docs.grid.ai/products/sessions/how-to-ssh-into-a-session)
- `grid session` [here](https://docs.grid.ai/products/global-cli-configs/cli-api/grid-interactive#ssh)

### Expected behavior

For consistency, have both `session` and `interactive` in the `grid --help` or use `grid session` in the docs to match the GUI terminology

### Current behavior

`grid --help` does not show `session` as a valid command.  The `interactive` is shown as the valid command

```bash
grid --help
Usage: grid [OPTIONS] COMMAND [ARGS]...

  Grid CLI

Options:
  --debug  Used for logging additional information for debugging purposes.
  --help   Show this message and exit.

Commands:
  artifacts    Downloads artifacts for a given run or experiments.
  cancel
  credentials  Manages credentials in Grid
  datastores   Manages datastore workflows in Grid
  delete
  history      View list of historic Runs.
  interactive  Displays interactive nodes for given project.
  login        Login into Grid AI.
  logs         Gets logs from an experiment.
  metrics      Gets metric values from an experiment.
  ssh-keys     Manage SSH keys in Grid
  status       Checks the status of Runs and Experiments.
  train        Trains scripts in remote infrastructure
  version      Prints CLI version to stdout
  view
```

**Comment by sunitaprakash** [comment]
@robert-s-lee Thank you for reporting this issue!  
Yes grid session and grid interactive are interchangeable.

**Comment by sunitaprakash** [comment]
@robert-s-lee The new style formatting for CLI --help with the latest release has session mentioned in it.
