### ISSUE TITLE
Julia example with a bayesian estimation example

### ISSUE THREAD

**Issue by jlperla** [gridai/gridai#63]
For Julia support it would be great to have a non-trivial example setup in a way that parallels how you might actually want to write the code.

Here is a good start: https://github.com/HighDimensionalEconLab/TuringCLIExample  which you can take over and move to your own repo if you wish (just tell me and I can remove it)

Hopefully it is clear, and I have the tensorboard/argparse etc. working roughly correct.  But I suspect there are still issues.  A few things you would want for a demo/test:
- Don't forget to do the `julia -e 'using Pkg; Pkg.add(\"IJulia\")'` or whatever to install the jupyter kernel for interactive use.  Note that this should be done in image building process WITHOUT the `--project` because you want this in the global namespace namespace
- Of course, instantiate this in the image building with `julia --threads auto --project -e 'using Pkg; Pkg.instantiate()'`   This you want to do with the `--project` activated so that it instals and compiles the right stuff.
-  Make sure it actually works and that it stores the output in the `tensorboard_logs` etc. correctly.  If not, talk to the turing team.  Feel free to change that location, of course.
- The `--project` argument for the julia pretty much always should be there, but you could give some options if you wished
- The `--threads` argument would be something you need to modify when calling grid.  I think that `--threads auto` is probably a good baseline though, but if you are doing distributed chaines/etc. it might not be what you want.
  -  I wasn't sure your architecture for configuration of the container environments when setting up runs, but I think that you should ahve a `--threads` option which can be overwritten.
- I would make sure that grid is picking up the artifacts correctly, which should include the tensorboard logs, an image for the traceplot, and a CSV file of some of the results.  We could add more just to check.
- The tensorboard UI should be able to show the arguments you would pass, but you should also make sure that you can see the aggregate output from this  - i.e., it is parsing the logfile correctly.  It would be great if it gets these things directly fro the turing output, but I added in https://github.com/HighDimensionalEconLab/TuringCLIExample/blob/main/src/TuringCLIExample.jl#L59-L70  just in case.  You would want to see the `XXX_ess_per_sec` and `XXX_rhat` for each of the variables you are estimating in the grid web UI display.  It would also be great to see the mean and std etc. as well.  But just something.
- I would make sure that the tensorboard GUI within grid's web shows the chain as it is running
- You should probably show how to download the artifacts in a shell script.  Later, it would be awesome to hint that you could generate a huge number of parallel chains and then have a script which downloads them all and does the mapreduce/etc. on the output.  To me, this is the mind-blowing thing with grid and bayesian stuff, especially if you are able to compile most of the stuff into the container binary so julia isn't doing all sorts of compilation while it executes.
- If you have issues with the errors when trying to generate the plots in the container, it may be because you need some binary dependencies for GR (which is used to generate the plots, and needs a few things to run headless that could be missing).  You can ask on Julia about that but I think it might be `apt install libxt6 libxrender1 libxext6 libgl1-mesa-glx libqt5widgets5`
- I would triple check that the container you build has done the `using Pkg; Pkg.instantiate()` etc. correctly, and that you are getting that stuff built into the image.  Otherwise, it could take a longtime to download and install all of the packages each time.  Later can examine a flag to invoke the packagecompiler on it.  For example, https://github.com/lanl-ansi/PowerModelsONM.jl/blob/master/Dockerfile#L14 is doing it, as are lots of others.  But it will take a few tweaks to get it working.  After that, Julia would be blindingly fast after starting up the container because it wouldn't need to compile everything.

**Comment by Sunitagrid** [comment]
@jlperla Thank you for reporting the feature request ! We will look into it

**Comment by sunitaprakash** [comment]
Check the docs for examples to run with Julia [](https://docs.grid.ai/products/run-run-and-sweep-github-files/running-julia-programs#step-3-bonus-cli-examples).  Better examples will be added later
