### ISSUE TITLE
[docs] `grid session` is missing in the help message

### ISSUE THREAD

**Issue by akihironitta** [gridai/gridai#67]
## 🐛 Bug
The explanation of `session` is missing in the `Commands` section as shown below:

### Expected behavior
To have `session` in the help message.

### Current behavior
```console
$ grid --help
Usage: grid [OPTIONS] COMMAND [ARGS]...

  Grid CLI

Options:
  --debug  Used for logging additional information for debugging purposes.
  --help   Show this message and exit.

Commands:
  artifacts    Downloads artifacts for a given run or experiments.
  cancel
  credentials  Manages credentials in Grid
  datastores   Manages datastore workflows in Grid
  delete
  history      View list of historic Runs.
  interactive  Displays interactive nodes for given project.
  login        Login into Grid AI.
  logs         Gets logs from an experiment.
  metrics      Gets metric values from an experiment.
  ssh-keys     Manage SSH keys in Grid
  status       Checks the status of Runs and Experiments.
  train        Trains scripts in remote infrastructure
  version      Prints CLI version to stdout
  view
```

### To Reproduce
See above.

### Environment
 - OS (e.g., Windows): Debian GNU/Linux
 - Browser (e.g., Chrome, Safari): n/a
 - CLI version: v0.3.70

### Additional context
Haven't checked, but there might be more missing.

**Comment by sunitaprakash** [comment]
@akihironitta Thanks for reporting the issue. We are working on getting CLI --help better. Interactive and session are same will make sure we add session in the help.
This issue was already by some other user (https://github.com/gridai/gridai/issues/61(url)) so will close this issue

**Comment by akihironitta** [comment]
Sorry I made a duplicate issue (^^;)

**Comment by sunitaprakash** [comment]
@akihironitta No worries ... keep using the product and please let us know the issues.

**Comment by sunitaprakash** [comment]
@akihironitta The new style formatting for CLI --help with the latest release has session mentioned in it.

**Comment by akihironitta** [comment]
@sunitaprakash Thanks a lot for keeping me updated :) I'll give a try!
