### ISSUE TITLE
(Very) Large numbers of Experiments cannot be cancelled via UI

### ISSUE THREAD

**Issue by mlw214** [gridai/gridai#68]
## 🐛 Bug

I launched a large hyper-parameter sweep (336 total combinations, meant to run a random search, but ran a full grid) and when I went to stop them via the UI, it failed to do so, even after many attempts. Eventually the stop button greyed out, but a large number of the experiments were still queued or running. I had to go to the cli app to stop everything fully. I tried using both Firefox (on Ubuntu) and Edge (on macOS), and neither worked.

### Expected behavior

When you cancel a large number of experiments via the UI, they are all cancelled in a timely manner.

### Current behavior

Either the cancellation is ignored, or only a subset are actually cancelled.

### To Reproduce

Launch a (very) large number of experiments under one run and attempt to cancel them via the UI.

### Environment

 - OS (e.g., Windows): Ubuntu 20.04/macOS 10.15
 - Browser (e.g., Chrome, Safari): Firefox/Edge
 - CLI version: v0.3.70

### Additional context

During my attempts to cancel these experiments, I got a lot of "Grid is not available" error messages. Unsure if it's related to this.

**Comment by essiequoi** [comment]
Hi @mlw214 thanks for opening this and sorry to hear about this experience. We'll investigate this ASAP. To be clear, were you able to get your experiments to actually cancel by using the CLI?

**Comment by mlw214** [comment]
Yes, thankfully! The CLI seems to work consistently.

**Comment by sunitaprakash** [comment]
@mlw214 The fix for this issue is now in production. Appreciate your patience while we resolved the issue.
