### ISSUE TITLE
Stdout Logs aren't viewable

### ISSUE THREAD

**Issue by mlw214** [gridai/gridai#69]
## 🐛 Bug

I can only view the stdout logs early on in an experiment's execution: after a certain amount of time, they become unviewable even if the experiment is still running. I'm using PyTorch Lightning, so it outputs a progress bar, which I can see early on in a run. Additionally, when attempting to get the logs via the cli, the following error occurs: `Error: {'message': 'WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason'}`

### Expected behavior

I can view the stdout logs of an experiment throughout its lifetime.

### Current behavior

The stdout logs disappear after a certain amount of time.

### To Reproduce

Steps to reproduce the issue

Run a PyTorch Lightning experiment, and after ~10-20 minutes, go view the stdout logs either via the UI or cli.

### Environment

 - OS (e.g., Windows): Ubuntu 20.04
 - Browser (e.g., Chrome, Safari): Firefox
 - CLI version: v0.3.70

**Comment by sunitaprakash** [comment]
@mlw214 Thanks for opening the issue .. We will investigate and get back to you.

**Comment by nmiculinic** [comment]
@mlw214 

* Is the behavior observed immediately (i.e. you run experiment for a while, then you see some logs, and then things stop working)

> they become unviewable even if the experiment is still running

Are the logs working as expected once the experiment completes?

**Comment by nmiculinic** [comment]
@mlw214 

* Is the behavior observed immediately (i.e. you run experiment for a while, then you see some logs, and then things stop working)

> they become unviewable even if the experiment is still running

Are the logs working as expected once the experiment completes?

**Comment by nmiculinic** [comment]
Also for which experiment have you observed such behavior?

**Comment by mlw214** [comment]
It's been consistent across all experiments I've run. And yes, the general flow of behavior is: I run an experiment and can immediately see stdout logs (both via CLI and UI); however, after 10 to 20 minutes they disappear (and that websocket error starts appearing with the CLI).

Interestingly, a portion of the logs are viewable after the experiment completes. For example, I had an experiment run for 12 epochs, and I can see the logs up to epoch 3.

**Comment by pchitale1** [comment]
Sorry for this issue. We are working on a fix for it and will let you know when it is available.

**Comment by sunitaprakash** [comment]
@mlw214 Closing the issue as the problem has not been seen after changes to Stdout log
