### ISSUE TITLE
Missing credential region in both ui and tui

### ISSUE THREAD

**Issue by ChenghaoMou** [gridai/gridai#70]
## 🐛 Bug

Credential region is missing in both the web ui and cli.

### Expected behavior

Credential region is displayed in the web ui and cli.

### Current behavior

![image](https://user-images.githubusercontent.com/32014649/119920058-8370d280-bf20-11eb-9f28-48c6ff865044.png)
![image](https://user-images.githubusercontent.com/32014649/119920068-87045980-bf20-11eb-8281-b26a776fa370.png)

### To Reproduce

Steps to reproduce the issue

`grid credentials`

### Environment

 - OS (e.g., Windows): macOS
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version: Grid CLI (v0.3.70)

### Additional context

NA

**Comment by sunitaprakash** [comment]
@ChenghaoMou Thanks for reporting the Issue. Why would you need the region information for your credential?

**Comment by ChenghaoMou** [comment]
Forgot to mention, it is a required information in the grid config/yaml file.

**Comment by sunitaprakash** [comment]
@ChenghaoMou Thanks we will be fixing this our next release

**Comment by sunitaprakash** [comment]
@ChenghaoMou  region is not a required filed in grid config/yaml file... would you still need the region information. The default region is set us-east-1.
