### ISSUE TITLE
git push in session is getting 403 error 

### ISSUE THREAD

**Issue by sunitaprakash** [gridai/gridai#76]
## 🐛 Bug

Reported by Dan Biderman
I tried to git push to my remote branch got:
remote: Permission to danbider/pose-estimation-nets.git denied to danbider... The requested URL returned error: 403
and then I got thrown out of the session. Dan's session is a public session

**Comment by luiscape** [comment]
In order to be able to push, one has to have activated the GitHub integration. GitHub needs that in order to accept pushes to its repository.

Is that active?

**Comment by sunitaprakash** [comment]
Dan the workaround to do git push to your branch , you need to delete the .git-credentials and then follow the steps to  generate a personal access token as per these instructions:
[https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token. ](url)
